#!/bin/bash

# install cassandra on nodes c1 c2 c3 c4
# it assumes you can run ssh root@c1 etc

for node in c1 c2 c3 c4
do
  echo	
  echo "node: $node"
  ssh -n root@$node "apt install openjdk-8-jre 
    echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | tee -a /etc/apt/sources.list.d/cassandra.sources.list 
    curl https://www.apache.org/dist/cassandra/KEYS | apt-key add - 
    apt-get update 
    apt-get install cassandra cassandra-tools
    service cassandra stop
    rm -rf /var/lib/cassandra/*
    cp /etc/cassandra/cassandra.yaml /etc/cassandra/cassandra.yaml.orig "

  scp cassandra.yaml root@$node:/etc/cassandra/cassandra.yaml

  # make c4 in another datacenter
  if [ "$node" = "c4" ] 
  then
      ssh -n root@$node sed -i -e 's/dc1/dc2/' /etc/cassandra/cassandra-rackdc.properties 
  fi
  ssh -n root@$node service cassandra start


  [ "$node" = "c1" ] && sleep 120

done

ssh -n root@c1 "cqlsh -u cassandra -p cassandra c1 -e \"ALTER KEYSPACE system_auth WITH REPLICATION = {'class' : 'NetworkTopologyStrategy', 'dc1' : 3, 'dc2' : 1 };\""

ssh root@c1 nodetool status


